Numpy Arrayleri Olusturma

In [146]:
import numpy as np
import time

Q.1

vektor bir boyutludur, matris cok boyutludur.

Q.2

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Q.3

In [6]:
a=np.zeros((10,10),dtype='int32')
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

Q.4

In [8]:
a=np.ones((10,10),dtype='float32')
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

Q.5

In [10]:
a=np.full((10,10),9, dtype='int32')
a

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]], dtype=int32)

Q.6

In [11]:
a=np.arange(5,25,3)
a

array([ 5,  8, 11, 14, 17, 20, 23])

Q.7

In [12]:
a=np.linspace(-1,1,30)
a

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

Q.8

In [14]:
a=np.random.randint(0,30,(5,6))
a

array([[12,  3,  2, 26,  9, 28],
       [12,  9, 16, 13, 19, 22],
       [14,  7,  2, 15, 15, 26],
       [10, 29, 12, 24, 22, 25],
       [21, 23, 27, 10, 16,  1]])

Q.9

In [15]:
a=np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Q.10

In [16]:
a=np.random.randint(0,10,(5,10))
a.ndim


2

In [17]:
a.shape

(5, 10)

In [18]:
a.size

50

In [19]:
a.dtype

dtype('int64')

Q.11

In [20]:
a=np.random.randint(10,size=(3,4,7))
a

array([[[2, 4, 4, 1, 4, 3, 5],
        [9, 4, 4, 9, 2, 2, 9],
        [2, 1, 3, 5, 7, 8, 4],
        [7, 8, 5, 7, 8, 5, 2]],

       [[5, 8, 4, 5, 3, 8, 5],
        [7, 4, 0, 5, 5, 8, 6],
        [4, 3, 3, 7, 2, 2, 7],
        [8, 3, 8, 8, 9, 5, 7]],

       [[7, 3, 9, 5, 3, 5, 3],
        [0, 9, 5, 3, 7, 4, 2],
        [7, 0, 5, 6, 9, 3, 9],
        [1, 6, 1, 9, 4, 6, 2]]])

Q.12

In [21]:
a=np.arange(1,10)
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Q.13

In [22]:
a=np.array([1])
b=np.array([2,3])
c=np.array([4,5,6])
d=np.array([7,8,9,10])
np.concatenate([a,b,c,d])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Q.14

In [31]:
a=np.random.randint(10,size=(3,3))
b=np.random.randint(10,size=(3,3))
np.concatenate([a,b], axis=1)

array([[6, 8, 0, 1, 3, 1],
       [4, 5, 7, 4, 5, 8],
       [8, 6, 1, 4, 4, 5]])

Q.15

axis=0 satir bazli, axis=1 sutun bazli birlestirme yapar

Q.16

In [32]:
a=np.random.randint(10,size=(1,3))
b=np.random.randint(10,size=(3,3))
np.vstack([a,b])

array([[6, 9, 4],
       [8, 6, 1],
       [2, 0, 6],
       [0, 9, 3]])

In [51]:
a=np.random.randint(10,size=(2,3))
b=np.random.randint(10,size=(2,5))
np.hstack([a,b])

array([[6, 6, 9, 8, 4, 1, 4, 5],
       [1, 0, 4, 5, 6, 1, 0, 4]])

Q.17

In [48]:
a=np.arange(1,10)
np.split(a,[1,4,7])

[array([1]), array([2, 3, 4]), array([5, 6, 7]), array([8, 9])]

Q.18

In [53]:
a=np.random.randint(10,size=10)
np.sort(a)


array([1, 2, 4, 4, 5, 6, 6, 6, 9, 9])

Q.19

In [55]:
a=np.random.randint(10,size=20)
a[3],a[5],a[7]

(6, 1, 7)

Q.20

In [56]:
a=np.random.randint(10,size=10)
a

array([8, 1, 1, 3, 3, 1, 9, 3, 4, 2])

In [57]:
a[3]=4
a

array([8, 1, 1, 4, 3, 1, 9, 3, 4, 2])

Q.21

diagonal matrix= 
trace matrix=

Q.22

In [63]:
a=np.eye(5, dtype='int32')
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [64]:
a[0,0],a[1,1],a[2,2],a[3,3],a[4,4]

(1, 1, 1, 1, 1)

Q.23

In [65]:
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [66]:
a[3:]

array([13, 14, 15, 16, 17, 18, 19])

Q.24

In [69]:
a=np.random.randint(10,size=(10,10))
a

array([[1, 3, 3, 7, 6, 4, 9, 1, 8, 1],
       [3, 5, 8, 0, 7, 4, 1, 9, 3, 6],
       [5, 6, 3, 0, 9, 0, 6, 0, 4, 0],
       [0, 1, 2, 1, 9, 7, 8, 1, 0, 3],
       [8, 9, 1, 4, 5, 5, 9, 9, 7, 6],
       [7, 9, 2, 8, 3, 5, 1, 7, 5, 2],
       [6, 7, 8, 8, 0, 9, 7, 3, 2, 8],
       [4, 3, 3, 3, 1, 6, 2, 0, 9, 3],
       [3, 2, 5, 5, 5, 6, 6, 9, 3, 2],
       [2, 4, 5, 5, 3, 7, 7, 3, 8, 1]])

In [70]:
a[3,5]

7

In [71]:
a[:,5]

array([4, 4, 0, 7, 5, 5, 9, 6, 6, 7])

In [72]:
a[2,:]

array([5, 6, 3, 0, 9, 0, 6, 0, 4, 0])

In [73]:
a[2:7,:]

array([[5, 6, 3, 0, 9, 0, 6, 0, 4, 0],
       [0, 1, 2, 1, 9, 7, 8, 1, 0, 3],
       [8, 9, 1, 4, 5, 5, 9, 9, 7, 6],
       [7, 9, 2, 8, 3, 5, 1, 7, 5, 2],
       [6, 7, 8, 8, 0, 9, 7, 3, 2, 8]])

In [74]:
a[2:5,3:7]

array([[0, 9, 0, 6],
       [1, 9, 7, 8],
       [4, 5, 5, 9]])

In [75]:
a[5:,:4]

array([[7, 9, 2, 8],
       [6, 7, 8, 8],
       [4, 3, 3, 3],
       [3, 2, 5, 5],
       [2, 4, 5, 5]])

Q.25

In [76]:
a=np.arange(0,50,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [77]:
np.sum(a>20)

5

In [78]:
np.sum(a<30)

6

In [79]:
np.sum(a==33)

0

In [80]:
a*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [81]:
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

Q.26

In [102]:
a=np.random.uniform(-1,1,30)
a

array([-0.49305988, -0.21785494,  0.83647281, -0.34982269, -0.45290901,
       -0.33082289,  0.52322973,  0.12730589, -0.63028358, -0.7270938 ,
        0.74806723, -0.66191932, -0.27948317,  0.32872598, -0.31185381,
       -0.03116714, -0.93116985,  0.6427058 , -0.75298924, -0.84580949,
       -0.58816292,  0.46790828,  0.38501296, -0.46024581,  0.30554453,
       -0.36273573,  0.36031284, -0.46660391,  0.63487425,  0.98544433])

In [103]:
np.mean(a)

-0.08494608481641427

In [104]:
np.std(a)

0.5520530695044517

In [105]:
np.var(a)

0.304762591549287

In [106]:
np.median(a)

-0.29566849122980177

In [107]:
np.min(a)

-0.9311698478483714

In [108]:
np.max(a)

0.9854443295999795

# Master Odev 10X10

In [155]:
k=0
start_time=time.time()
while True:
    a=np.random.random((10,10))
    b=np.random.random((10,10))
    c=a-b
    diagonal=np.diag(c)
    k=k+1
    if np.all((diagonal > -0.1) & (diagonal < 0.1))==True:
        break
end_time=time.time()

print(c,"\n")
print(diagonal,"\n")
print(str(k)+' loops in '+str(end_time-start_time)+ ' seconds')
    

[[ 3.23306841e-02  5.74997862e-01  1.80166074e-01 -1.42689741e-01
  -2.67097389e-01  2.25082905e-02  4.92831106e-02 -3.97926066e-01
  -1.73877654e-01 -1.08539804e-01]
 [ 1.25450954e-03  5.51779926e-02  5.74400057e-01 -8.65824526e-01
  -2.84254856e-01 -9.24466014e-02 -5.09144429e-02  5.86640819e-01
  -1.15150003e-01  1.53660293e-01]
 [ 1.66874769e-01 -5.53320896e-02  6.28202067e-02  5.99389526e-02
   6.48177148e-01  4.63576733e-01  5.18907634e-01  5.68546532e-01
  -2.64672404e-01 -2.97420173e-01]
 [ 4.91836114e-01  1.83468309e-01  3.20137342e-01  1.21473902e-02
  -2.39003323e-01  2.55178968e-01 -5.14537482e-01 -3.64488608e-02
   2.04340178e-01 -2.05066780e-01]
 [ 1.95981417e-01 -2.30616911e-01  9.30846650e-01 -4.64455204e-01
   3.99298277e-03  9.47248132e-02 -5.43421258e-02 -4.98224024e-01
   5.43152940e-01  6.40805553e-01]
 [-2.07179378e-02  5.42666885e-01  4.27755482e-02 -3.84585550e-02
   6.21900694e-01 -4.91123112e-02  5.77508190e-01 -4.10436151e-02
   8.05737460e-01 -4.23559546e-01