In [1]:
# !pip install numpy

In [1]:
#jupyter nbconvert --to html notebook.ipynb

In [4]:
import numpy as np 

In [55]:
#ornek-1
#Normal yollardan listenin her elemanini birbiri ile carpalim.

a = [1,2,3,4]
b = [2,3,4,5]

                     

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [7]:
# Ayni islemi hatta daha fazlasini Numpy ile yapalim.

a = np.array([1,2,3,4])

b = np.array([2,3,4,5])

c = np.array([5,6,3,0])

a * b * c    # iki veriyi indexli carpma islemi yapar

array([10, 36, 36,  0])

In [2]:
#ornek-2 her listenin son elemanlarina ulasin. ilkel yontem
a = [[1,23,4],
     [5,6,7],
     [89,9,99]]
liste = []

for i in range(len(a)):
    liste.append(a[i][2])

print(liste)


[4, 7, 99]


In [5]:
# Numpy ile  her listenin son elemanlarina ulasin. 
a = np.array([[1,23,4],
              [5,6,7],
              [89,9,99]])

a[:,-1]  #son sutundaki elemanlara ulasir

array([ 4,  7, 99])

In [8]:
# ornek-3
a = np.array([[1,23,4],
              [5,6,7],
              [89,9,99]])
a*5

array([[  5, 115,  20],
       [ 25,  30,  35],
       [445,  45, 495]])

# NumPy Arrayleri Oluşturma

### Listelerden Array Oluşturmak

In [5]:
import numpy as np 

a = np.array([12,33,4,5])  # tekboyutlu
a


array([12, 33,  4,  5])

In [9]:
type(a)

numpy.ndarray

In [81]:
# numpy array olusturma bu sekilde olur > np.array([....])

a = np.array([3.14, 4, 6, 1.2])
a 

#ciktida hepsi float oldu.

array([3.14, 4.  , 6.  , 1.2 ])

In [12]:
#tipini degistirme

np.array([3.14, 4, 6.,2], dtype = 'float32')    # icerisindeki tum elemanlarin type float32 yapar yada int32

array([3.14, 4.  , 6.  , 2.  ], dtype=float32)

In [13]:
#sifirlardan array olusturma

np.zeros((5,3), dtype = 'int32')    # sadece sifirlardan olusan 5 x 3 lu int veri array olusturur dtype default floattur


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
# Birlerden array olusturma

np.ones((2,3))  # sadece 1 lerden  olusan 2x3 (matris) int veri arrayi olusturur.

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
#istedigimiz degerden array olusturma

np.full((6,7),9)         # 6 ye 7 lik matrislerden icinde 9 olan array olusturur

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [11]:
np.arange(0,10,2)     # 0 dan 10 kadar 2ser 2ser giden bir array olusturur, tek boyutlu son dizin dahil degil

array([0, 2, 4, 6, 8])

In [17]:
np.linspace(-1,1,30)   # 0 ile 1 arasinda 30 adet dizi olusturur.  bolumu 30'a boler ve ondalikli sayilar olusturur

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [23]:
np.random.randint(0,10, (2,2))     # 0 ile 10 arasinda integerlardan olusan 2 ye 2lik bir matris olusturur. Degerler rastgele secilir. 

array([[0, 7],
       [4, 5]])

In [120]:
np.eye(5)        # 5x5lik kosegenleri 1 olan bir matris olusturur, eyedentidi matris

                 # buna  DIAGONAL / birim matris de denir.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Numpy Biçimlendirme

* **ndim**: boyut sayısı

* **shape**: satir ve sutun bilgisini verir, kaclik matris

* **size**: toplam eleman sayısı

* **dtype**: array veri tipi

In [36]:
import numpy as np

a = np.random.randint(6, size =10)   # 0 dan 6'a kadar random size = 10 adet veri olusturur, 
a

array([4, 5, 1, 4, 0, 5, 1, 5, 0, 4])

In [37]:
print("Boyut sayisi =  ",a.ndim) 
print("satir, sutun bilgisi =  ",a.shape)  #BOYUT BILGISI ? 
print("Toplam eleman sayisi =  ",a.size)
print("Veri tipi =  ",a.dtype)

Boyut sayisi =   1
satir, sutun bilgisi =   (10,)
Toplam eleman sayisi =   10
Veri tipi =   int32


In [122]:
a = np.random.randint(10, size = (10, 5))
a

array([[5, 3, 3, 9, 6],
       [4, 4, 7, 8, 9],
       [1, 3, 9, 8, 3],
       [4, 8, 3, 1, 3],
       [7, 1, 8, 5, 3],
       [0, 5, 6, 1, 6],
       [5, 6, 5, 3, 9],
       [6, 5, 3, 0, 9],
       [6, 2, 8, 1, 2],
       [3, 4, 9, 9, 0]])

In [123]:
a.ndim #Boyut sayisi

2

In [19]:
a.shape # satir sutun

(10, 5)

In [20]:
a.size   #eleman sayisi

50

In [21]:
a.dtype   # veri type

dtype('int32')

In [21]:
a = np.random.randint(10, size = (2,4,7))   # 2 TANE 3 boyutlu array (adet, satir, sutun)

a

array([[[6, 8, 8, 8, 3, 5, 0],
        [5, 7, 2, 9, 0, 6, 5],
        [1, 5, 6, 3, 4, 8, 7],
        [7, 5, 2, 0, 8, 2, 3]],

       [[3, 9, 2, 0, 1, 0, 8],
        [7, 3, 8, 7, 0, 9, 4],
        [5, 4, 3, 0, 9, 6, 0],
        [7, 5, 6, 8, 5, 7, 6]]])

In [150]:
a.ndim

3

In [151]:
a.shape

(2, 4, 7)

In [152]:
a.size

56

In [153]:
a.dtype

dtype('int32')

In [27]:
np.arange(1,10)   # 1 den 10 a kadar tek boyutlu array olusturur.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#vektorleri matrise cevirme

np.arange(1,10).reshape(3,3)   # tek bouyutlu arrayi, 3 boyutlu matrise cevirdik. 3x3=9 adet eleman olmak zorunda


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a = np.array([1,2,3,5,6,7,8,9,0])        #tek boyutlu array,

In [45]:
a

array([1, 2, 3, 5, 6, 7, 8, 9, 0])

In [49]:
b = a.reshape((3,3))   # tek boyutlu arrayi 3e 3luk matrise cevirdik   3x3 = 9 adet eleman olmak zorunda
b

 # Not = [[]] demek 2 boyutlu demek, [] tek boyutlu demek

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [162]:
b.ndim   # boyut sayisi

2

In [163]:
a.ndim

1

## birlestirme islemleri

In [1]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

NameError: name 'np' is not defined

In [2]:
x

NameError: name 'x' is not defined

In [3]:
y

NameError: name 'y' is not defined

In [54]:
np.concatenate([x,y])   # iki arrayi birlestirme islemi yapar []

array([1, 2, 3, 4, 5, 6])

In [40]:
z = [1,2,3]

In [41]:
np.concatenate([x,y,z])   # 3 arrayi birlestirdi

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [42]:
#iki boyutlu

In [58]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
np.concatenate([a,a], axis = 1)   # birlestirme islemini yatay (sutun) olarak yapar  1 sutun, 0satir

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [46]:
#farklı boyutlu  vektor ve matrisleri birlestirme

In [47]:
a = np.array([1, 2, 3])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])

In [48]:
a #  tek boyutlu

array([1, 2, 3])

In [49]:
b  # iki boyutlu

array([[9, 8, 7],
       [6, 5, 4]])

In [50]:
np.vstack([a,b])   # farkli boyutlu arraylari SATIR BAZLI birlestirme yapar

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [165]:
a = np.array([[99],
              [99]])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])

In [52]:
np.hstack([a,b])   # yatay SUTUN BAZLI bir sekilde birlestirme yapar,

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

## array ayirma splitting

In [12]:
x = [1, 2, 3, 99, 99, 3, 2, 1,33,4,567,112,4678,33]
x

[1, 2, 3, 99, 99, 3, 2, 1, 33, 4, 567, 112, 4678, 33]

In [13]:
np.split(x, [3,6,9])  

# x i 4 parcaya bolecek ve ilkini 3.indexten bolecek, sonra 6.indexten bolecek, sonra 9 dan bolecek 
#cikan sonuclar array type olacak.

[array([1, 2, 3]),
 array([99, 99,  3]),
 array([ 2,  1, 33]),
 array([   4,  567,  112, 4678,   33])]

In [55]:
a,b,c,d = np.split(x, [3,6,9])   # bolunme isleminde olusan arraylari sirasiyla a b c d ye atadik

In [56]:
print(a,b,c,d)

[1 2 3] [99 99  3] [ 2  1 33] [   4  567  112 4678   33]


##  array siralama 

In [18]:
import numpy as np
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [19]:
np.sort(v)   # kucukten siralama yapar ama ana veriyi bozmaz

array([1, 2, 3, 4, 5])

In [20]:
v

array([2, 1, 4, 3, 5])

In [21]:
v.sort()  # kucukten siralama yapar ama ana veri bozulur. bu yuzden tercih edilmez

In [22]:
v

array([1, 2, 3, 4, 5])

# NumPy Eleman İşlemleri

## Index ile Elemanlara Erişmek

In [78]:
import numpy as np
a = np.random.randint(10, size = 10)    # 0 dan 10 akadar random size = 10 adet veri olusturur, 
a

array([6, 8, 1, 6, 1, 1, 2, 3, 5, 9])

In [79]:
a[0]   # a nin 0.indexine (ilk elemana ) ulasir

6

In [80]:
a[-2]   # tersten 2. elemana ulasir 

5

In [81]:
a[0] = 1  # a nin  0. indexindeki elemani degistirdik. 1 yaptik

In [82]:
a

array([1, 8, 1, 6, 1, 1, 2, 3, 5, 9])

In [68]:
a = np.random.randint(10, size = (3, 5))   #3x5 iki boyutlu matris
a

array([[8, 9, 9, 1, 1],
       [4, 6, 0, 4, 3],
       [2, 2, 3, 0, 2]])

In [69]:
a[1,1]   # iki boyutlu elamanlara eristik. 1. satir ve 1.sutundaki elemana ulasir

6

In [71]:
a[1,3]   # 1.satir, 3.sutun

4

In [86]:
a[0,0] = 1  # 0.satir ve 0.sutundaki elemani degistir. 1 yap

In [87]:
a[0,0]

1

In [88]:
a[0,0] = 2.2   #array int oldugu icin flout bile gondersek o integer olarak atayacak. 

In [89]:
a[0,0] 

2

## Slicing ile Array Alt Kümesine Erişmek

In [2]:
import numpy as np
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [91]:
a[0:3]   # 0dan 3 e kadar elemanlari  alir (index olarak)

array([20, 21, 22])

In [92]:
a[:3]    # en bastan 3. indexe kadar alir

array([20, 21, 22])

In [93]:
a[3:]  # 3.indexten sonuna kadar alir

array([23, 24, 25, 26, 27, 28, 29])

In [94]:
a[::2]   # en bastan baslar en sona kadar 2ser 2ser atlayarak gider

array([20, 22, 24, 26, 28])

In [95]:
a[1::2]     # 1.indexten baslar sonuna kadar gider  2ser 2ser atlayarak gider

array([21, 23, 25, 27, 29])

In [96]:
a[2::2]    # 2.indexten baslar sonuna kadar gider  2ser 2ser atlayarak gider

array([22, 24, 26, 28])

In [97]:
a[1::3]     # 1.indexten baslar sonuna kadar gider  3ser 3ser atlayarak gider

array([21, 24, 27])

In [72]:
a = np.random.randint(10, size = (5, 5))
a

array([[6, 7, 7, 2, 6],
       [8, 9, 6, 8, 8],
       [6, 1, 0, 9, 0],
       [2, 2, 1, 6, 4],
       [1, 6, 6, 6, 1]])

In [73]:
a[:,0]    
# 0.sutunun tum satirlarini secer

array([6, 8, 6, 2, 1])

In [74]:
a[:,1]   # 1.sutunun tum satirlarini secer

array([7, 9, 1, 2, 6])

In [77]:
a[:,4]   # 4.sutunun tum satirlarini secer

array([6, 8, 0, 4, 1])

In [9]:
a

array([[7, 7, 1, 1, 8],
       [6, 5, 6, 1, 2],
       [4, 7, 8, 5, 1],
       [1, 1, 6, 0, 3],
       [4, 1, 3, 8, 0]])

In [10]:
a[4,:]   # tum sutunlarin 4.satirini alir

array([4, 1, 3, 8, 0])

In [11]:
a[0]  # 0.satirin tum sunutlarini verir. Ilk satirin tamami

array([7, 7, 1, 1, 8])

In [15]:
a[1]  # 1.satirin tum sunutlarini verir. ikinci  satirin tamami

array([6, 5, 6, 1, 2])

In [106]:
a[2]  # 2.satirin tum sutunlarini verir. ucuncu satirin tamami

array([8, 1, 6, 5, 6])

In [107]:
a[:2,:3]   # 0dan 2 yekadar olan satirlarin : 0dan 3 e kadar olan sutunlari secer   son degerler dahil degil

array([[2, 8, 7],
       [3, 8, 7]])

In [108]:
a[0:2,0:3]  # 0dan 2 yekadar olan satirlarin : 0dan 3 e kadar olan sutunlari secer   son degerler dahil degil

array([[2, 8, 7],
       [3, 8, 7]])

In [18]:
a[:,:2]     # tum satirlarin ilk iki sutununu secti

array([[7, 7],
       [6, 5],
       [4, 7],
       [1, 1],
       [4, 1]])

In [110]:
a[:,:2]     # tum satirlarin ilk iki sutununu secti, ustteki ile ayni islemi yapar

array([[2, 8],
       [3, 8],
       [8, 1],
       [6, 0],
       [1, 5]])

In [111]:
a[1:3,0:2]   # 1den 3 e kadar olan satirlarini secer  :  0dan 2 ye kadar olan satirlarin, 

array([[3, 8],
       [8, 1]])

In [112]:
a = np.random.randint(10, size = (5, 5))  # 0 den 10a kadar  5x5 lik matris olusturur.
a

array([[9, 9, 5, 2, 7],
       [1, 0, 7, 0, 3],
       [2, 7, 7, 5, 6],
       [4, 4, 1, 8, 2],
       [3, 0, 8, 8, 6]])

In [113]:
alt_a = a[0:3,0:2]   # secilen araliklari yeni bir nesne olarak tanimlayabiliriz.

In [114]:
alt_a

array([[9, 9],
       [1, 0],
       [2, 7]])

In [115]:
alt_a[0,0] = 9999  # 0. satir ve 0.sutundaki elemani 9999 yaptik
alt_a[1,1] = 9999   # 1. satir ve 1.sutundaki elemani 9999 yaptik.

In [116]:
alt_a

array([[9999,    9],
       [   1, 9999],
       [   2,    7]])

In [117]:
alt_b = a[0:3,0:2].copy()    # ana verimizde degisiklige sebep olmasin diye .copy() kullanmak cok faydadlidir

In [118]:
alt_b

array([[9999,    9],
       [   1, 9999],
       [   2,    7]])

In [119]:
alt_b[0,0] = 9999
alt_b[1,1] = 9999

In [120]:
a   # ana verimizin degismedigini gorecegiz. ana veri ham haliyle bir yerlerde kalmasi guzel olur. 

array([[9999,    9,    5,    2,    7],
       [   1, 9999,    7,    0,    3],
       [   2,    7,    7,    5,    6],
       [   4,    4,    1,    8,    2],
       [   3,    0,    8,    8,    6]])

## Fancy Index ile Eleman İşlemleri

Sadece belirli indexleri sececeksek bu yontem Fancy Indexleme kullanilir,

In [23]:
v = np.arange(0, 30, 3)  # 0dan 30a kadar 3 er atlayarak array olusturur
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [24]:
v[1]  # 1. indexe ulasir
v[3]  # 3. indexe ulasir

9

In [123]:
[v[1], v[3]]   # 1 ile 3 e ulasir

[3, 9]

In [124]:
### Sadece belirli indexleri sececeksek bu yontem Fancy Indexleme kullanilir,

al_getir = [1,3,5]   # secmek istedigimiz indexler
v[al_getir]         # sectigimiz indexlerin degerleri  bu ikisi beraber kullanilarak index degerleri getirilir.

array([ 3,  9, 15])

In [125]:
m = np.arange(9).reshape((3, 3))   #3x3 matris
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
m[0, [0,2]]   # m deki 0.satiri ve 0 ve 2.sutunlari sectik sadece 0 ve 2. sutunlari aldi. aralik degil!  

array([0, 2])

In [130]:
m[0:,[0,1,2]]   # Tum satirlari aldik   : 1 ve 2. sutundaki 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Koşullu Eleman İşlemleri

!! Ciktilar True ve False doner.

In [137]:
v = np.array([1,2,3,4,5])

In [138]:
v > 3   # v de 3den buyuk olanlari doner, True yada False doner

array([False, False, False,  True,  True])

In [139]:
v < 3   # v de 3den kucuk olanlari doner, True yada False doner.

array([ True,  True, False, False, False])

In [140]:
v <= 3     # v de 3den kucku esit  olanlari doner, True yada False doner

array([ True,  True,  True, False, False])

In [141]:
v == 3   # v de 3'e esit olanlari doner, True yada False doner

array([False, False,  True, False, False])

In [142]:
v != 3    # v de 3 esit olmayanlari doner, True yada False doner

array([ True,  True, False,  True,  True])

In [143]:
(2 * v)  # tum elemanlari 2 ile carpar

array([ 2,  4,  6,  8, 10])

In [144]:
(v ** 2)   # tum elemanlarin karesini alir

array([ 1,  4,  9, 16, 25], dtype=int32)

In [145]:
(2 * v) == (v ** 2)  

array([False,  True, False, False, False])

#ufunc yani arkada donusum yaparak bu islemler yapilir

- np.equal
- np.not_equal
- np.less
- np.less_equal
- np.greater
- np.greater_equal

In [146]:
v = np.array([1,2,3,4,5])

In [147]:
np.equal(3,v)   # arka tarafta boyle bi fonksiyon calisir. ornek olsun diye yazdik

array([False, False,  True, False, False])

In [23]:
v = np.random.randint(0, 10, (3, 3))
v

array([[7, 8, 8],
       [3, 6, 0],
       [6, 1, 0]])

In [151]:
v > 5   # 5den buyuk olanlari T F doner

array([[False, False, False],
       [ True, False,  True],
       [ True,  True,  True]])

In [152]:
np.sum(v > 5)    # 5den buyuk donen T F larin kac tane True oldugunu toplayip soyler. Yani n kadar True var demek

5

In [25]:
np.sum((v > 3) & (v < 7))     

# 3den buyuk  've'  7 den kucuk kac True var. sadece True lari sayir !!! ( & = and anlamindadir)

2

In [154]:
(v > 3) & (v < 7)      

array([[False,  True, False],
       [False, False, False],
       [ True, False,  True]])

In [28]:
np.sum((v > 3) | (v < 7))    

# 3den buyuk "veya" 7 den kucuk kac True var. sadece True lari sayar !!! ( | = or anlamindadir )

9

In [29]:
v = np.random.randint(0, 10, (3, 3))
v

array([[3, 8, 6],
       [8, 9, 0],
       [9, 8, 7]])

In [30]:
np.sum(v > 4, axis = 1)      

# sadece satirlardaki 4 den buyuk olanlari doner ve toplar. yani her satirda kac tane bu kosulu saglayan deger var bunun sayisini verir.
# degerin kendisini vermez. 

array([2, 2, 3])

In [31]:
np.sum(v > 4, axis = 0)  

# sadece sutunlarda 4 den buyuk olanlari doner ve toplar. yani her satirda kac tane bu kosulu saglayan deger var bunun sayisini verir.
# degerin kendisini vermez. 

array([2, 3, 2])

In [158]:
np.all(v > 4)  # verideki tum elemanlarin  4 den buyuk olup olmadigini sorgular, hepsi 4 den buyukse TRUE FALSE doner

False

In [159]:
np.all(v > 0)   # verideki tum elemanlarin  4 den buyuk olup olmadigini sorgular, hepsi 4 den buyukse TRUE FALSE doner

True

In [160]:
np.any(v > 4)  

# veride en az bir tane  4 den buyuk eleman olup olup olmadigini sorgular, 
#en az bir tane varsa TRUE FALSE doner

True

In [161]:
np.all(v > 4, axis = 0)    # sadece sutun bazinda 4 den buyuk eleman olup olmadigini sorgular. hepsi 4den buyukse True doner

array([False, False, False])

In [162]:
np.all(v > 4, axis = 1)    # sadece satir bazinda 4 den buyuk eleman olup olmadigini sorgular. hepsi 4den buyukse True doner

array([False, False,  True])

# NumPy Hesaplamalı İşlemler

In [167]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [168]:
a - 1   # a daki elemanlarin hepsinden 1 cikarir, 

array([-1,  0,  1,  2,  3])

In [169]:
a / 2   # a daki elemanlarin hepsini 2 ye boler, 

array([0. , 0.5, 1. , 1.5, 2. ])

In [170]:
a * 5   # a daki elemanlarin hepsini 5 ile carpar, 

array([ 0,  5, 10, 15, 20])

In [171]:
a ** 2   # a daki elemanlarin hepsinin karesini alir, 

array([ 0,  1,  4,  9, 16], dtype=int32)

In [172]:
a % 2    # a daki elemanlarin hepsinden 2 ye bolumunden kalanlari soyler, 

array([0, 1, 0, 1, 0], dtype=int32)

### matematiksel islemleri fonksiyonlarla yapalim

In [175]:
np.add(a,2) #toplama

array([2, 3, 4, 5, 6])

In [176]:
np.subtract(a,1)  #cikarma

array([-1,  0,  1,  2,  3])

In [177]:
np.multiply(a,3)   #carpma

array([ 0,  3,  6,  9, 12])

In [178]:
np.divide(a,3)    # bolme

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [179]:
np.power(a,3)   # karesini alir

array([ 0,  1,  8, 27, 64], dtype=int32)

In [32]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [33]:
np.add.reduce(a)   # tum degerleri birbiri ile toplar 

15

In [182]:
np.add.accumulate(a)   

# tum degerleri birbiri ile toplar asamalari da gosterir. carma bolme ve digerleri icinde ayni islemler yapilabilir

array([ 1,  3,  6, 10, 15], dtype=int32)

In [183]:
a = np.random.normal(0, 1, 30)
a

array([ 0.96330095, -2.65028546,  0.48465968, -2.16993144, -0.84664791,
       -0.8077067 , -1.21253367,  0.5172644 ,  1.86563977, -1.18631636,
       -0.46175309, -0.21980735,  2.49061843, -0.45389654,  1.92737038,
        1.08488105, -1.44562986,  0.74449396, -1.93281108,  1.81832147,
        1.55739968,  0.24207704, -1.21787026,  0.67594409, -0.10559448,
       -1.44589828, -1.67853852, -0.27579593,  0.59992636, -0.86764262])

In [184]:
np.mean(a)   # a nin ortalamasini verir

-0.1335587420158523

In [185]:
np.std(a)   # a nin standart sapmasini verir

1.3182836532328035

In [186]:
np.var(a)   # a nin varyansini verir

1.7378717903808267

In [187]:
np.median(a)  # a nin median degerini verir. en orta deger

-0.24780163594271426

In [188]:
sum(a)  # normal sekilde toplama yaptik

-4.006762260475568

In [189]:
np.min(a)   # en kucuk deger tek boyutlu

-2.650285457563394

In [190]:
np.max(a) # en buyuk deger tek boyutlu

2.4906184272442062

In [191]:
a = np.random.normal(0, 1, (3,3))
a

array([[-0.99390265, -0.98896969,  1.09002242],
       [-1.4952012 , -1.13494252, -1.47431805],
       [ 0.81339126,  0.7714917 ,  1.48480632]])

In [192]:
a.sum()   # a yi toplar

-1.9276223942552848

In [193]:
a.sum(axis = 1)   # satir bazinda toplama yapar

array([-0.89284991, -4.10446177,  3.06968928])

In [3]:
a.sum(axis = 0)   # sutun bazinda toplama yapar

245